name: Deploy to AWS

on:
  push:
    branches:
      - main  # Trigger on main branch pushes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/amazon-ecs-cli@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Upload to S3
        run: |
          aws s3 sync build/ s3://crud-app-awais --delete

      - name: Configure S3 Website Hosting
        run: |
          aws s3 website s3://crud-app-awais/ --index-document index.html --error-document index.html

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E32KA00UKLA296 --paths "/*"
